Add some changes on BoardConfig.mk
Galaxy-MT6768/android_device_samsung_a31nsxx pull request #14
Opened 2024-04-26 15:42 UTC by Igorpetinik

2024-04-26 17:36 UTC, DevZillion requested changes
ptal

2024-04-26 17:36 UTC, DevZillion commented on BoardConfig.mk
> +# TW_Y_OFFSET := 80
Uncomment the screen offsets

2024-04-26 17:36 UTC, DevZillion commented on BoardConfig.mk
> -
Please avoid removing the blank line at the end of the file :)

2024-05-03 11:12 UTC, Igorpetinik reviewed
Fix

2024-05-06 10:25 UTC, closed without merging